spring.application.name=medcheck

spring.datasource.url=jdbc:${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

jwt.signing.key=${JWT_SIGNING_KEY}

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG

server.tomcat.max-parameter-count=10000

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB


spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=2

CLOUDINARY_URL=${CLOUDINARY_URL}

server.address=0.0.0.0
server.port=${PORT:8080}
