spring.application.name=medcheck

spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

spring.jpa.open-in-view=false
spring.jackson.time-zone=UTC

jwt.signing.key=${JWT_SIGNING_KEY}
jwt.duration=${JWT_DURATION}
cloudinary.url=${CLOUDINARY_URL}

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=debug
logging.level.com.yrsd.medcheck=DEBUG
server.tomcat.max-parameter-count=10000

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB


spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=2



VERIFICATION_CODE_LENGTH=${VERIFICATION_CODE_LENGTH}
#Turning off Spring Security Error informing us that we are using a customized authentication filter
logging.level.org.springframework.security.config.annotation.authentication.configuration.InitializeUserDetailsBeanManagerConfigurer=ERROR

server.address=0.0.0.0
server.port=${SERVER_PORT:8080}

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}


spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.port=${RABBITMQ_PORT}
spring.rabbitmq.username=${RABBITMQ_USERNAME}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}


